/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FueliPicliMinter } from "./FueliPicliMinter";
export type { IFueli } from "./IFueli";
export type { IPicli } from "./IPicli";
