/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as minterSol from "./Minter.sol";
export type { minterSol };
import type * as multicallSol from "./Multicall.sol";
export type { multicallSol };
export type { Fueli } from "./Fueli";
export type { FueliDAO } from "./FueliDAO";
export type { Picli } from "./Picli";
