/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
export type { IERC4906 } from "./IERC4906";
export type { IERC5267 } from "./IERC5267";
export type { IERC5805 } from "./IERC5805";
export type { IERC6372 } from "./IERC6372";
